# ===============================
# = PROD
# ===============================
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: A$dmin123

    platform : mysql
    initialization-mode : always
