# ===============================
# = DEV
# ===============================
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false
    # Windoows
    # url : jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false&serverTimezone=UTC
    username: root
    password:

    platform: mysql
    initialization-mode: always
